name: Deploy para PRD e Aviso no Discord

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm test

      - name: Deploy para PRD
        run: |
          echo "Rodando deploy..."
          # Coloque aqui seu script real de deploy
          sleep 5
          echo "Deploy concluído!"

      - name: Avisar no Discord
        if: success()
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          COMMIT_URL="https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"
          AUTHOR_URL="https://github.com/${GITHUB_ACTOR}"

          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{
                    \"embeds\": [{
                      \"title\": \"🚀 Deploy para PRD concluído com sucesso!\",
                      \"color\": 3066993,
                      \"fields\": [
                        {\"name\": \"Repositório\", \"value\": \"${GITHUB_REPOSITORY}\", \"inline\": true},
                        {\"name\": \"Branch\", \"value\": \"prd\", \"inline\": true},
                        {\"name\": \"Autor\", \"value\": \"[${GITHUB_ACTOR}](${AUTHOR_URL})\", \"inline\": true},
                        {\"name\": \"Commit\", \"value\": \"[${COMMIT_MSG}](${COMMIT_URL})\"}
                      ],
                      \"timestamp\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"
                    }]
                  }" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
