name: Aviso de PRD no Discord

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checar código
        uses: actions/checkout@v4

      - name: Avisar no Discord
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B | tr -d '\r')
          COMMIT_URL="https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"
          AUTHOR_URL="https://github.com/${GITHUB_ACTOR}"

          curl -H "Content-Type: application/json" -X POST \
               -d "{
                    \"embeds\": [{
                      \"title\": \"🚀 Push em PRD\",
                      \"description\": \"Código atualizado no branch **prd**.\",
                      \"color\": 3066993,
                      \"fields\": [
                        {\"name\": \"Repositório\", \"value\": \"${GITHUB_REPOSITORY}\", \"inline\": true},
                        {\"name\": \"Autor\", \"value\": \"[${GITHUB_ACTOR}](${AUTHOR_URL})\", \"inline\": true},
                        {\"name\": \"Commit\", \"value\": \"[${COMMIT_MSG}](${COMMIT_URL})\"}
                      ],
                      \"timestamp\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"
                    }]
                  }" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
