name: Aviso de PRD no Discord

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checar código
        uses: actions/checkout@v4

      - name: Avisar no Discord
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B | tr -d '\r')
          COMMIT_URL="https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"
          AUTHOR_URL="https://github.com/${GITHUB_ACTOR}"
          ZIP_BRANCH_URL="https://github.com/${GITHUB_REPOSITORY}/archive/refs/heads/prd.zip"
          ZIP_COMMIT_URL="https://github.com/${GITHUB_REPOSITORY}/archive/${GITHUB_SHA}.zip"

          # Escapar aspas no commit message para JSON
          SAFE_COMMIT_MSG=$(printf '%s' "$COMMIT_MSG" | python3 -c 'import json,sys; print(json.dumps(sys.stdin.read())[1:-1])')

          curl -H "Content-Type: application/json" -X POST \
               -d "{
                    \"embeds\": [{
                      \"title\": \"🚀 Tema Atualizado\",
                      \"description\": \"Novo tema em adicionado em PRD.\",
                      \"color\": 3066993,
                      \"fields\": [
                        {\"name\": \"Autor\", \"value\": \"[${GITHUB_ACTOR}](${AUTHOR_URL})\", \"inline\": true},
                        {\"name\": \"Commit\", \"value\": \"[${SAFE_COMMIT_MSG}](${COMMIT_URL})\"},
                        {\"name\": \"Baixar Tema\", \"value\": \"[Download](${ZIP_COMMIT_URL})\", \"inline\": true}
                      ],
                      \"timestamp\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"
                    }]
                  }" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
